spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.232.200:3306/school?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    druid:
      filters: stat,wall
      aop-patterns: com.rain.admin.*
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
      filter:
        wall:
          config:
            delete-allow: false
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
mybatis-plus:
  mapper-locations: classpath:mapper\*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

